{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "07af6436",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from typing import List\n",
    "from langchain_community.document_loaders import UnstructuredFileLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from langchain_community.vectorstores import Chroma\n",
    "import chromadb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d82d2700",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 1. CONFIGURATION ---\n",
    "CHROMA_HOST = os.getenv(\"chroma_server\", \"localhost\")\n",
    "CHROMA_PORT = os.getenv(\"chroma_port\", \"8000\")\n",
    "COLLECTION_NAME = \"enterprise_knowledge\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "209a23aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 2. INITIALIZE EMBEDDINGS ---\n",
    "# Consistent with the RAG node to ensure vector space alignment\n",
    "embeddings = HuggingFaceEmbeddings(model_name=\"sentence-transformers/all-MiniLM-L6-v2\")\n",
    "\n",
    "client = chromadb.HttpClient(host=CHROMA_HOST, port=CHROMA_PORT)\n",
    "\n",
    "vector_db = Chroma(\n",
    "    collection_name=\"collection1\",\n",
    "    embedding_function=embeddings,\n",
    "    client=client\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "484914ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 3. CORE INGESTION LOGIC ---\n",
    "\n",
    "\n",
    "from langchain_community.document_loaders import UnstructuredURLLoader\n",
    "from langchain_community.tools.tavily_search import TavilyAnswer\n",
    "\n",
    "def ingest_web_url(url: str):\n",
    "    \"\"\"\n",
    "    Scrapes a live URL and adds it to the vector store.\n",
    "    \"\"\"\n",
    "    loader = UnstructuredURLLoader(urls=[url])\n",
    "    docs = loader.load()\n",
    "    \n",
    "    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)\n",
    "    chunks = text_splitter.split_documents(docs)\n",
    "    \n",
    "    # Use your defined chroma_client to sync\n",
    "    vector_db.add_documents(chunks)\n",
    "    return f\"URL {url} ingested successfully.\"\n",
    "\n",
    "# ADDING THE SEARCH TOOL FOR THE AGENT\n",
    "from langchain_community.tools.tavily_search import TavilySearchResults\n",
    "\n",
    "# Industry standard for agentic search\n",
    "search_tool = TavilySearchResults(k=3)\n",
    "\n",
    "\n",
    "def process_document(file_path: str):\n",
    "    \"\"\"\n",
    "    Handles PDF/Markdown/Docx ingestion using Unstructured.\n",
    "    Professional-grade partitioning for complex layouts.\n",
    "    \"\"\"\n",
    "    if not os.path.exists(file_path):\n",
    "        raise FileNotFoundError(f\"Source file not found: {file_path}\")\n",
    "\n",
    "    # Use Unstructured to handle layout-aware partitioning\n",
    "    # 'elements' mode preserves hierarchy better than 'single'\n",
    "    loader = UnstructuredFileLoader(\n",
    "        file_path,\n",
    "        strategy=\"fast\",  # Use \"hi_res\" if you need OCR for scanned PDFs\n",
    "        mode=\"elements\",\n",
    "    )\n",
    "\n",
    "    raw_docs = loader.load()\n",
    "\n",
    "    # Recursive splitting is the industry standard for maintaining context\n",
    "    text_splitter = RecursiveCharacterTextSplitter(\n",
    "        chunk_size=1000, chunk_overlap=150, add_start_index=True\n",
    "    )\n",
    "\n",
    "    chunks = text_splitter.split_documents(raw_docs)\n",
    "\n",
    "    # Add metadata for search filtering (Enterprise standard)\n",
    "    for chunk in chunks:\n",
    "        chunk.metadata[\"source\"] = os.path.basename(file_path)\n",
    "\n",
    "    return chunks\n",
    "\n",
    "\n",
    "def sync_to_vector_db(chunks: List):\n",
    "    \"\"\"\n",
    "    Syncs processed chunks to a remote Vector DB instance.\n",
    "    \"\"\"\n",
    "    # Connect to a persistent Chroma instance (Render-compatible)\n",
    "    client = chromadb.HttpClient(host=CHROMA_HOST, port=CHROMA_PORT)\n",
    "\n",
    "    vectorstore = Chroma(\n",
    "        client=client, collection_name=COLLECTION_NAME, embedding_function=embeddings\n",
    "    )\n",
    "\n",
    "    # Batch upsert to prevent API timeouts on large documents\n",
    "    vectorstore.add_documents(chunks)\n",
    "    print(f\"Successfully ingested {len(chunks)} chunks into {COLLECTION_NAME}.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d02c064",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 4. EXECUTION ---\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # In a real-world scenario, this is triggered by a webhook or S3 event\n",
    "    target_file = \"data/knowledge_base.pdf\"\n",
    "\n",
    "    try:\n",
    "        doc_chunks = process_document(target_file)\n",
    "        sync_to_vector_db(doc_chunks)\n",
    "    except Exception as e:\n",
    "        print(f\"Ingestion failed: {str(e)}\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
